# JEE Aplication Stack for Development
# run docker-compose up --build from the commandline

version: '2.0'

services:
  wildfly:
    build: docker/wildfly
    ports:
      - 8080:8080
      - 9990:9990
      - 8787:8787
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  www:
    build: docker/nginx
    ports:
      - 80:80
    volumes:
      - ./www:/usr/share/nginx/html
    depends_on:
      - wildfly
  mysql:
    build: docker/mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    build: docker/phpmyadmin
    ports:
      - 5050:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
volumes:
  mysql_data:


